const kategoriKeywords = {
    "LAIN-LAIN": ["PESARA", "PENGETUA KOLEJ KEJURAWATAN", "KEM BINA NEGARA (BANG.BARU)"],
    "DAERAH JABATAN PENGAIRAN": ["DAERAH JABATAN PENGAIRAN"],
    "PEGAWAI DAERAH": [
        "JURUTERA DAERAH HULU", "KETUA PEN PEGAWAI DAERAH", "KETUA PENOLONG PEGAWAI DAERAH", "PEG DAERAH", "PEGAWAI DAERAH", "PEN PEGAWAI DAERAH", "PENOLONG PEGAWAI DAERAH", "PEJABAT DAERAH LARUT MATANG", "KETUA PENOLONG PEGAWAI PEJABAT DAERAH"
    ],
    "RUKUN TETANGGA": ["KAWASAN RUKUN TETANGGA", "RUKUN TETANGGA", "PENGURUS RUKUN TETANGGA", "PENGERUSI RUKUN TETANGGA", "PENGERUSI R.TANGGA"],
    "AGENSI ANTI DADAH": ["ANTI DADAH", "AGENSI ANTI DADAH", "ANTIDADAH"],
    "AKADEMI PEMBANGUNAN BELIA MALAYSIA": ["AKADEMI PEMBANGUNAN BELIA"],
    "ANGKATAN TENTERA DARAT": ["ANGKATAN TENTERA DARAT", "TDM"],
    "ASRAMA AMANJAYA HARMONI": ["ASRAMA AMANJAYA HARMONI"],
    "BELIA DAN SUKAN": ["BELIA DAN SUKAN", "PENGARAH INSTITUT KEMAHIRAN BELIA"],
    "BIRO TATANEGARA": ["BIRO TATANEGARA", "BIRO TATANEGARA JAB", "PEN PENGARAH BIRO"],
    "BOMBA PERAK": ["BOMBA"],
    "FEDERAL AGRICULTURAL MARKETING AUTHORITY": ["FEDERAL AGRICULTURAL MARKETING "],
    "FELCRA": ["FELCRA"],
    "FELDA": ["FELDA", "FGV AGRI SERVICES"],
    "IADA KERIAN": ["IADA KERIAN"],
    "INSTITUT DARUL RIDZUAN BERHAD": ["INSTITUT DARUL RIDZUAN"],
    "JABATAN AGAMA ISLAM PERAK": ["JABATAN AGAMA ISLAM "],
    "JABATAN HAL EHWAL KHAS": ["JABATAN HAL EHWAL "],
    "JABATAN HUTAN": ["JABATAN HUTAN", "PERHUTANAN", "PEJABAT HUTAN"],
    "JABATAN IMIGRESEN": ["JABATAN IMIGRESEN", "IMIGRESEN"],
    "JABATAN KEBAJIKAN MASYARAKAT": ["JABATAN KEBAJIKAN MASYARAKAT", "KEBAJIKAN MASYARAKAT"],
    "JABATAN KERJA RAYA": ["JABATAN KERJA RAYA", "KERJA RAYA", "JKR", "KETUA JURUTERA ELEKTRIK NEGERI", "KETUA JURUTERA", "KETUA JURUTERA JKR", "KETUA JURUTERA JKR NEGERI PERAK", "KETUA JURUTERA JKR PERAK", "JURUTERA JKR", "JABATAN KERJA RAYA", "JURUTERA DAERAH KINTA"],
    "JABATAN METEOROLOGI PERAK": ["METEOROLOGI", "JABATAN METEOROLOGI", "JABATAN METEOROLOGI PERAK"],
    "JABATAN PENDAFTARAN NEGARA": ["JABATAN PENDAFTARAN NEGARA", "PENDAFTARAN NEGARA"],
    "JABATAN PENJARA MALAYSIA": ["JABATAN PENJARA MALAYSIA", "PENJARA MALAYSIA", "PENJARA"],
    "JABATAN PERPADUAN NEGARA": ["JABATAN PERPADUAN NEGARA", "PERPADUAN NEGARA", "PERPADUAN"],
    "JABATAN PERTANIAN": ["JABATAN PERTANIAN", "PERTANIAN"],
    "JABATAN PERUMAHAN NEGARA": ["JABATAN PERUMAHAN NEGARA", "PERUMAHAN NEGARA"],
    "JABATAN SUKARELAWAN MALAYSIA(RELA)": ["JABATAN SUKARELAWAN MALAYSIA", "SUKARELAWAN MALAYSIA", "RELA"],
    "JABATAN WARISAN NEGARA": ["JABATAN WARISAN NEGARA", "WARISAN NEGARA"],
    "JAKOA": ["JAKOA", "ORANG ASLI", "JABATAN KEMAJUAN ORANG ASLI", "ORG ASLI", "JABATAN KEMAJUAN ORANG ASLI PERAK", "JABATAN KEMAJUAN ORANG ASLI NEGERI PERAK", "JABATAN KEMAJUAN ORANG ASLI NEGERI"],
    "KEMENTERIAN KESIHATAN": ["KESIHATAN", "KKM", "KLINIK", "HOSPITAL", "PENGARAH LPPKN"],
    "KEMENTERIAN PENDIDIKAN": ["KEMENTERIAN PENDIDIKAN", "KPM", "PELAJARAN", "PENDIDIKAN"],
    "KEMENTERIAN PERTAHANAN": ["PERTAHANAN", "ANGKATAN PERTAHANAN AWAM", "KEMENTERIAN P'TAHANAN"],
    "KETUA KAMPONG": ["KETUA KAMPONG", "KETUA KAMPUNG"],
    "LEMBAGA AIR PERAK": ["LEMBAGA AIR PERAK", "LAP"],
    "LEMBAGA KEMAJUAN IKAN MALAYSIA": ["KEMAJUAN IKAN MALAYSIA", "LKIM PERAK"],
    "LEMBAGA KOKO MALAYSIA": ["LEMBAGA KOKO MALAYSIA", "KOKO MALAYSIA", "PENGURUS LEMBAGA KOKO"],
    "LEMBAGA MINYAK SAWIT MALAYSIA": ["LEMBAGA MINYAK SAWIT"],
    "LEMBAGA PEMASARAN PERTANIAN PERSEKUTUAN": ["LEMBAGA PEMASARAN PERTANIAN"],
    "LEMBAGA PERUMAHAN DAN HARTANAH PERAK": ["LEMBAGA PERUMAHAN DAN HARTANAH PERAK", "PERUMAHAN DAN HARTANAH"],
    "KEMAS": ["KEMAS"],
    "MARA": ["MARA", "INSTITUT MARA", "GIATMARA", "MAJLIS AMANAH RAKYAT(MARA)", "PUSAT GIAT", "MRSM", "MAJLIS AMANAH RAKYAT"],
    "MAJLIS AGAMA ISLAM": [
        "MAJLIS AGAMA ISLAM", "MAJLIS AGAMA ISLAM PERAK", "PEGAWAI TADBIR AGAMA", "MAIPK", "MAIP", "MAJLIS AGAMA ISLAM PERAK", "MAJLIS AGAMA ISLAM DAN ADAT MELAYU PERAK", "MAJLIS HAL EHWAL AGAMA", "PEJABAT AGAMA ISLAM", "PEJABAT AGAMA ISLAM", "AGAMA ISLAM", "PEJABAT AGAMA DAERAH"
    ],
    "MAJLIS BANDARAYA IPOH": ["MAJLIS BANDARAYA IPOH", "MBI"],
    "MAJLIS DAERAH BATU GAJAH": ["MAJLIS DAERAH BATU GAJAH", "MAJLIS DAERAH BARAT", "MAJLIS DAERAH KINTA BARAT", "YANG DIPERTUA MAJLIS DAERAH BATU GAJAH", "YANG DIPERTUA MDBG", "YANG DIPERTUA MAJLIS DAERAH KINTA BARAT"],
    "MAJLIS DAERAH GERIK": ["MAJLIS DAERAH GERIK", "MAJLIS DAERAH PENGKALAN HULU", "YANG DIPERTUA MDPH"],
    "MAJLIS DAERAH KAMPAR": ["MAJLIS DAERAH KAMPAR", "YANG DIPERTUA MAJLIS DAERAH KAMPAR"],
    "MAJLIS DAERAH KERIAN": ["MAJLIS DAERAH KERIAN", "YANG DIPERTUA MAJLIS DAERAH KERIAN", "YANG DIPERTUA MDK"],
    "MAJLIS DAERAH LENGGONG": ["MAJLIS DAERAH LENGGONG", "YANG DIPERTUA MAJLIS DAERAH LENGGONG"],
    "MAJLIS DAERAH PERAK TENGAH": ["MAJLIS DAERAH PERAK TENGAH", "MDPT"],
    "MAJLIS DAERAH SELAMA": ["MAJLIS DAERAH SELAMA", "YANG DIPERTUA MAJLIS DAERAH SELAMA"],
    "MAJLIS DAERAH TANJONG MALIM": ["MAJLIS DAERAH TANJONG MALIM", "YANG DIPERTUA MAJLIS DAERAH TANJONG MALIM", "YANG DIPERTUA MDHS", "YANG DIPERTUA MDTM"],
    "MAJLIS DAERAH TAPAH": ["MAJLIS DAERAH TAPAH", "YANG DIPERTUA MAJLIS DAERAH TAPAH", "YANG DIPERTUA MDT"],
    "MAJLIS PERBANDARAN KUALA KANGSAR": [
        "MPKK", "KUALA KANGSAR", "MAJLIS PERBANDARAN KUALA KANGSAR", "KANGSAR", "YANG DIPERTUA MAJLIS PERBANDARAN", "YANG DIPERTUA MDKK"
    ],
    "MAJLIS PERBANDARAN MANJUNG": ["MAJLIS PERBANDARAN MANJUNG", "MPM"],
    "MAJLIS PERBANDARAN TAIPING": ["MAJLIS PERBANDARAN TAIPING", "MPT"],
    "MAJLIS PERBANDARAN TELUK INTAN": ["MAJLIS PERBANDARAN TELUK INTAN", "YANG DIPERTUA MDHP", "YANG DIPERTUA MPTI", "MAJLIS DAERAH HILIR", "MAJLIS PERBANDARAN HILIR PERAK", "YDP MAJLIS DAERAH H PERAK", "YDP MDTI"],
    "MENTERI BESAR INCORPORATED": ["MENTERI BESAR INCORPORATED"],
    "NR MANAGEMENT CONSULTANT NADI VILLA": ["NR MANAGEMENT CONSULTANT NADI VILLA"],
    "PEGAWAI PEMERINTAH": ["PEGAWAI PEMERINTAH", "PEGAWAI PEMTRINTAH"],
    "PEGAWAI PENJAGA": ["PEGAWAI PENJAGA"],
    "PEJABAT DAERAH DAN TANAH": [
        "PEJABAT DAERAH & TANAH", "PEJABAT DAERAH DAN TANAH", "PEJABAT TANAH DAN DAERAH", "PEJABAT TANAH", "PEJABAT DAERAN & TANAH", "PEJABAT DAERAN & TANAH KINTA"
    ],
    "PEJABAT PENGHULU": ["PEJABAT PENGHULU", "PENGHULU", "PEJABAT PENGHULU MUKIM"],
    "PENGARAH PERIKANAN NEGERI PERAK": ["PENGARAH PERIKANAN NEGERI PERAK"],
    "PENGARAH PROJEK": ["PENGARAH PROJEK"],
    "PENGAWAI PEMERINTAH BATALION 3 PGA": ["PENGAWAI PEMERINTAH BATALION 3 PGA"],
    "PENGETUA KOLEJ MELAYU KUALA KANGSAR": ["PENGETUA KOLEJ MELAYU"],
    "PENGHULU": ["BALAI PENGHULU", "PENGHULU MUKIM"],
    "PENGARAH PROJEK PEMBANGUNAN": ["PENGH PJK PEMBANGUNAN", "PENGRAH PROJEK PEMBANGUNAN", "PENGARAH PROJEK PEMBANGUNAN", "PENGARAH PJK PEMBANGUNAN", "PGH PJK", "PGRH PJK PEMBANGUNAN", "PNGH PJK PEMBANGUNA", "PNGH PJK PEMBANGUNAN", "PENGARAH PJK PEMBANGUNAN", "PENGARAH PROJEK PEMBANGUNAN"],
    "PENGURUS LADANG INFOTERNA": ["PENGURUS LADANG INFOTERNA", "PENGURUS LADANG INFOTERNAK"],
    "PERBADANAN KEMAJUAN NEGERI PERAK": ["PERBADANAN KEMAJUAN EKONOMI", "PERBADANAN KEMAJUAN NEGERI", "PERBADANAN KEMAJUAN NG", "PERBADANAN KEMAJUAN"],
    "PERBADANAN MENTERI BESAR PERAK": ["PERBADANAN MENTERI BESAR"],
    "PERBADANAN PEMBANGUNAN BANDAR": ["PERBADANAN PEMBANGUNAN BANDAR"],
    "PERBADANAN PEMBANGUNAN PERTANIAN NEGERI PERAK": ["PERBADANAN PEMBANGUNAN PERTANIAN"],
    "PERBADANAN PERPUSTAKAAN AWAM": ["PERPUSTAKAAN AWAM", "PERBADANAN PERPUSTAKAN AWAM"],
    "PERBADANAN PERWIRA HARTA MALAYSIA": ["PERBADANAN PERWIRA HARTA"],
    "PERKESO": ["PERTUBUHAN KESELAMATAN SOSIAL", "PERKESO"],
    "PERTUBUHAN PELADANG": ["PELADANG"],
    "PERTUBUHAN SRITI MALAYSIA": ["PERTUBUHAN SRITI MALAYSIA"],
    "PIHAK BERKUASA PELAKSANAAN KORIDOR UTARA": ["PIHAK BERKUASA PELAKSANAAN"],
    "PKNP": ["PERBADANAN KEMAJUAN NEGERI PERAK", "PKNP", "P.K.N.P"],
    "POLIS PERAK": ["POLIS"],
    "POLITEKNIK": ["POLITEKNIK"],
    "PUSAT KHIDMAT KOMUNITI RELA": ["PUSAT KHIDMAT KOMUNITI RELA"],
    "RISDA": ["RISDA"],
    "SETIAUSAHA KERAJAAN NEGERI PERAK": ["SETIAUSAHA KERAJAAN NEGERI PERAK", "SETIAUSAHA KERAJAAN NEGERI", "SETIAUSAHA KERAJAAN", "SUK PERAK", "S/USAHA", "KERAJAAN NEGERI PERAK", "SUK"],
    "TABIKA PERPADUAN": ["TABIKA PERPADUAN"],
    "SEKOLAH": [
        "SEKOLAH", "SEKOLAH MENENGAH", "SEKOLAH RENDAH", "GURU BESAR", "MAAHAD", "MA'AHAD", "SCHOOL", "SJK", "PENGETUA", "PENGERUSI", "MADRASAH", "SEK", "S.R.K", "SRK", "SMA", "SABK", "SRJK", "SMJK", "SMK", "SK", "G/BESAR", "SRAR", "TADIKA", "TADIKAH", "TADIKA KEMAS", "TADIKA PERPADUAN", "TADIKA PERPADUAN KEMAS", "TADIKA KEMAS PERPADUAN", "S.M.J.K","SEK.MEN.AGAMA"
    ],
    "TNB": [
        "TENAGA NASIONAL BERHAD", "TNB", "STESEN JANAELEKTRIK", "TNBHSB"
    ],
    "UPEN": ["UPEN", "UNIT PERANCANG EKONOMI NEGERI PERAK", "UNIT PERANCANG EKONOMI"],
    "YAYASAN": ["YAYASAN"],
}

const keywordCategoryMap = {};
function matchWholeWord(haystack, needle) {
    // Escape regex special chars in needle
    const escapedNeedle = needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // Regex: match as a whole word, ignore case
    const regex = new RegExp(`\\b${escapedNeedle}\\b`, 'i');
    return regex.test(haystack);
}

function findCategoryByName(name) {
    if (!name) return 'LAIN-LAIN';
    const upperName = name.toUpperCase();

    for (const [category, keywords] of Object.entries(kategoriKeywords)) {
        for (const keyword of keywords) {
            if (matchWholeWord(upperName, keyword.toUpperCase())) {
                return category;
            }
        }
    }
    return 'LAIN-LAIN'; // Default if no match found
}


module.exports = { kategoriKeywords, keywordCategoryMap, findCategoryByName };