services:
  backend:
    image: hapejoy/status21-server:v3.1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: always

  frontend:
    image: hapejoy/status21-client:v3.1
    # Remove or comment out the ports section below if you only want access via Nginx
    # ports:
    #   - "8080:8080"
    environment:
      PORT: 8080
      API_URL: http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client-side/status21-app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge