# Docker Compose file for the Status21 application
services:
  backend:
    image: hapejoy/status21-server:latest
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always # Automatically restart the backend container

  frontend:
    image: hapejoy/status21-client:latest
    build:
      context: ./client-side/status21-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always # Automatically restart the frontend container

networks:
  app-network:
    driver: bridge