services:
  backend:
    image: hapejoy/status21-server:v2.0
    build:
      context: ./server-side
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always

  frontend:
    image: hapejoy/status21-client:v2.1 # Updated version
    build:
      context: ./client-side/status21-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge